export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';
export const IS_USER_DETAILS_STATE_CHANGED = 'IS_USER_DETAILS_STATE_CHANGED';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const GET_DARK_MODE_STATUS = 'GET_DARK_MODE_STATUS';
