export const REGISTER = 'REGISTER';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const SET_REGISTER_ERROR_MESSAGE = 'SET_REGISTER_ERROR_MESSAGE';
export const TOGGLE_PASSWORD_VISIBILITY = 'TOGGLE_PASSWORD_VISIBILITY';
export const TOGGLE_CONFIRM_PASSWORD_VISIBILITY =
  'TOGGLE_CONFIRM_PASSWORD_VISIBILITY';

export const REGISTER_ERROR_FIRST_NAME = 'REGISTER_ERROR_FIRST_NAME';
export const REGISTER_ERROR_LAST_NAME = 'REGISTER_ERROR_LAST_NAME';
export const REGISTER_ERROR_EMAIL = 'REGISTER_ERROR_EMAIL';
export const REGISTER_ERROR_PASSWORD = 'REGISTER_ERROR_PASSWORD';
export const REGISTER_ERROR_CONFIRM_PASSWORD =
  'REGISTER_ERROR_CONFIRM_PASSWORD';
