export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const GET_LOGIN_STATUS = 'GET_LOGIN_STATUS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOGIN_ERROR_EMAIL = 'LOGIN_ERROR_EMAIL';
export const LOGIN_ERROR_PASSWORD = 'LOGIN_ERROR_PASSWORD';
export const TOGGLE_PASSWORD_VISIBILITY = 'TOGGLE_PASSWORD_VISIBILITY';
